server:
  name: oracle-go
  # Global version output，eg： cli: oracle-go version
  version: 0.0.6

cli:
  name: oracle-go

log:
  level:
    server: info

eth:
  network: mainnet
  elAddr:
  clAddr:
  privateKey:

# oracle config
oracle:
  # Whether Oracle sends real data to the chain
  isReportData: true
  # Whether to turn on a transaction that only simulates reportData
  isSimulatedReportData: false