server:
  name: oracle-go
  # Global version output，eg： cli: oracle-go version
  version: 0.0.2-beta

cli:
  name: oracle-go

log:
  level:
    server: info

eth:
  network: mainnet
  elAddr:
  clAddr:
  privateKey: